#参考https://skyao.io/learning-hugo/theme/academic.html

# Configuration of Hugo
# Guide: https://sourcethemes.com/academic/docs/get-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "忐忑の博客"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com`.
baseurl = "https://twbworld.github.io/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = '[![](https://img.shields.io/badge/©-2020—{year}_By_忐忑-2962ff)](/authors/admin/) <br/> [![](https://img.shields.io/github/release/twbworld/hugo-blog)](https://github.com/twbworld/hugo-blog) [![](https://img.shields.io/badge/powered-hugo-ff4088)](https://gohugo.io/) [![](https://img.shields.io/badge/theme-hugo_academic-00d1b2)](https://sourcethemes.com/academic)'
#&copy; 2020-{year} [忐忑](/authors/admin/) Powered by the [Academic theme](https://sourcethemes.com/academic) for [Hugo](https://gohugo.io).

# google分析工具
# googleAnalytics = "17048c9d4209e5d08a9ae5b0b4160808"



############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "academic"

# 写文章不需要手动输入时间,借助git) Get last modified date for content from Git?
enableGitInfo = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "zh"
hasCJKLanguage = true  # 关系到summaryLength)Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

summaryLength = 30  # 文章列表的简介字数限制)Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate = 10  # Number of items per page in paginated lists.(分页)
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.
# 如果index.md没有设置slug,那么默认slug等于title,由于title是文章标题可能是中文,中文不利于 用在url 以及 SEO;其次文章标题可能多变,而目录名不多变以及url和目录名恰好要求是唯一的;所以这里干脆用filename,即目录名(程序员一般不会起中文名的目录)
# 也可以在index.md设置"url"参数,自定义url
[permalinks]
  post = "/post/:year/:month/:day/:filename"
  tags = "/tags/:title/"
  authors = "/authors/:title/"
  categories = "/categorys/:title/"
  publication_types = "/publication-types/:filename/"

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure the Markdown renderer.
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false # 有序列表

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  #category = "categories"
  #publication_type = "publication_types"
  #author = "authors"

# 文章底部的"相关"
# https://s0gohugo0io.icopy.site/content-management/related/
[related]
  threshold = 80.0
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "keywords"
    weight = 200.0
  [[related.indices]]
    name  = "tags"
    weight = 160.0
  [[related.indices]]
    name  = "date"
    weight = 10.0
    pattern = "2006"
  [[related.indices]]
    name = "title"
    weight = 60.0
  [[related.indices]]
    name = "summary"
    weight = 50.0
