# SITE SETUP
# Guide: https://sourcethemes.com/academic/docs/get-started/
# Documentation: https://sourcethemes.com/academic/docs/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[search]`).

############################
## Theme
############################

# Choose a theme.
#   Latest themes (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in themes in `themes/academic/data/themes/`
#   Browse user installed themes in `data/themes/`
theme: minimal

# Enable users to switch between day and night mode?
day_night: false

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font: ''

# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size: L

############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type: Person

# Local business type (optional)
# If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
local_business_type: ''

# Organization name (optional)
# Enter an organization or project name. Defaults to the site title from `config.toml`.
org_name: ''

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description: 忐忑的个人技术博客网站

############################
## Site Features
############################

# Enable source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight: true

# Add support for highlighting additional languages
# https://www.staticfile.org/
highlight_languages:
  - php
  - php-template
  - go
  - python
  - css
  - javascript
  - shell
  - bash
  - json
  - yaml
  - xml
  - nginx
  - sql

# 代码高亮主题-For supported styles, see https://cdnjs.com/libraries/highlight.js/
highlight_style: dracula

# Enable LaTeX math rendering? true/false
#   If false, you can enable math on a per page basis as needed.
math: false

# Enable diagram rendering? true/false
#   If false, you can enable diagrams on a per page basis as needed.
diagram: true

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack: false

# Enable visitors to edit pages?
#   `repo` defines the repository URL. `editable` defines which page types can be edited.
edit_page:
  repo_url: 'https://github.com/wowchemy/wowchemy-hugo-modules'
  content_dir: ''
  repo_branch: master
  editable:
    docs: true
    page: false
    post: false

# Show related content at the bottom of pages?
show_related:
  docs: false
  page: false
  post: true
  project: false
  publication: false
  talk: false

############################
## Contact details
##
## These details power the Contact widget (if enabled).
## Additionally, for organizations, these details may be used to enrich search engine results.
############################

# Enter contact details (optional). To hide a field, clear it to "".
email: 1174865138@qq.com
# phone : ""

# Address
# For country_code, use the 2-letter ISO code (see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 )
address:
  street: ''
  city: 广州
  region: 广东
  postcode: ''
  country: 中国
  country_code: CN

# Geographic coordinates
# To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
coordinates:
  latitude: '37.4275'
  longitude: '-122.1697'

# Directions for visitors to locate you.
# directions = "Enter Building 1 and take the stairs to Office 200 on Floor 2"
directions: ''

# Office hours
# 工作时间)A list of your office hours. To remove, set to an empty list `[]`.
# office_hours : ["Monday 10:00 to 13:00", "Wednesday 09:00 to 10:00"]
office_hours: ''

# Enter an optional link for booking appointments (e.g. calendly.com).
appointment_url: ''

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links:
  - icon: github
    icon_pack: fab
    name: DM Me
    link: 'https://github.com/twbworld'
  - icon: twitter
    icon_pack: fab
    name: DM Me
    link: 'https://twitter.com/twbworld'
  - icon: instagram
    icon_pack: fab
    name: DM Me
    link: 'https://www.instagram.com/twbworld'
  - icon: weibo
    icon_pack: fab
    name: 关注
    link: 'http://weibo.com/u/2646212535'
  - icon: zhihu
    icon_pack: fab
    name: 关注
    link: 'https://www.zhihu.com/people/tan-te-41'

# post页底部显示社交链接
post_share: false

############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/media/` folder and specify image name here.
sharing_image: avatar.jpg

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter: twbworld

############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
# date_format = "Jan 2, 2006"
date_format: '2006-01-02'

#   Examples: "3:04 pm" or "15:04"
# time_format: "3:04 PM"
time_format: '15:04'

# Address format (en-us, en-gb, de, fr-fr, zh).
address_format: zh

############################
## Advanced
############################

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu:
  enable: true
  align: c
  show_logo: true
  highlight_active_link: true
  show_language: false
  show_day_night: true
  show_search: true

# 显示帖子大概阅读时间)Show estimated reading time for posts? (true/false)
reading_time: true

# Display next/previous section pager? (true/false)
section_pager: false

# Display pager in Docs layout (e.g. tutorials)?
docs_section_pager: true

# Enable in-built social sharing buttons? (true/false)
sharing: true

# Show a copyright license from creativecommons.org in the site footer?
# Page specific copyright licenses are also possible by adding this option to a page's front matter.
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'

# Abstract length (characters) in the Compact and Portfolio Card list views. Also, see `summaryLength` in `config.toml`.
abstract_length: 135

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js: []

#文章底部是否显示访问量;与config.copyright配置协同
site_views: true

#静态资源使用的cdn地址,如https://cdn.jsdelivr.net/gh/twbworld/twbworld.GitHub.io@gh-pages/
cdn_site: 'https://cdn.jsdelivr.net/gh/twbworld/twbworld.GitHub.io@gh-pages'

# Avatars.
# An avatar is an image that appears next to a user's name.
# An avatar can be uploaded as an image named `avatar` to each user's profile or fetched from Gravatar.com.
avatar:
  gravatar: true # Get user avatars from Gravatar.com? (true/false)
  shape: circle # Choose a shape for avatar images. Options: circle, square.

# Configuration of publication pages.
publications:
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  # date_format = "January 2006"
  date_format: '2020-04-26'
  # Citation style ("apa" or "mla")
  citation_style: apa

# Configuration of project pages.
projects:
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view: 2
  publication_view: 2
  talk_view: 2

# Breadcrumb navigation
breadcrumb:
  page_types:
    book: true


############################
## Comments
############################
comments:
  # Comment provider:
  #   "": Disabled
  #   "disqus": Disqus (https://disqus.com)
  #   "commento": Commento (https://commento.io)
  #   "gitment": Gitment (https://github.com/imsun/gitment)
  provider: gitment

  # Which page types are commentable?
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true

  # Configuration of Disqus.
  disqus:
    shortname: twbworld # Paste the shortname from your Disqus dashboard.
    show_count: false # 这个会加载被墙的js资源,为加快速度改false)Show comment count in page header? (true/false)

  commento:
    # If self-hosting Commento, enter its URL here (e.g. "https://commento.?.com"), otherwise leave empty.
    url: ''

  # Configuration of gitment.
  # https://github.com/imsun/gitment
  # 登录账号,填写"认证回调地址"要注意,填写的是重定向后的域名
  gitment:
    owner: twbworld #GitHub用户名或用户ID,ID获取: https://api.github.com/users/[GitHub用户名]
    repo: twbworld.GitHub.io #repositories仓库名称
    client_id: 21184f6e00f998440f3a
    client_secret: 8f062db04079fdc954a43b6ab98b2ce2efdd4866

############################
## Search
############################
search:
  # Search provider:
  #   "": No search engine
  #   "wowchemy": Built-in search engine
  #   "algolia": Algolia (https://www.algolia.com)
  provider: wowchemy
  # 在什么页面关闭搜索icon,判断type
  unable_type:
    - page
  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false

############################
## Maps
############################
map:
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   "": No map
  #   "google": Google Maps
  #   "mapnik": OpenStreetMap (Mapnik)
  #   "mapbox": OpenStreetMap (Mapbox)
  provider: mapnik
  api_key: ''
  zoom: 15

############################
## Marketing
############################
# 填写了google_tag_manager就没必要填写google_analytics,因为GTM可以使用GA
# verification用于验证网站所属, 如果通过域名的方式验证, 那这个就不需要设置了
marketing:
  google_analytics: UA-165300316-1
  google_tag_manager: GTM-P8WL7G3
  google_site_verification: ''
  baidu_site_verification: ''
  google_optimize: OPT-T64TWGJ #https://optimize.google.com/

############################
## Content Management System
############################
cms:
  branch: master
  local_backend: false

############################
## Icon Pack Extensions
############################
icon:
  pack:
    ai: false # Academicons icon pack https://jpswalsh.github.io/academicons/

# 首页背景,此处自行添加的
home_background:
  # Apply a background color, gradient, or image.
  #   Uncomment (by removing `#`) an option to apply it.
  #   Choose a light or dark text color by setting `text_color_light`.
  #   Any HTML color name or Hex value is valid.

  # Background color.
  # color : navy

  # Background gradient.
  # gradient_start : "DeepSkyBlue"
  # gradient_end : "SkyBlue"

  # Background image.
  image: 'https://cdn.jsdelivr.net/gh/twbworld/hosting@master/img/20200505231535.jpg' # Name of image in `static/img/`.
  image_darken: 0.4 # Darken the image? Range 0-1 where 0 is transparent and 1 is opaque.
  image_size: cover # Options are `cover` (default), `contain`, or `actual` size.
  image_position: center # Options include `left`, `center` (default), or `right`.
  image_parallax: true # Use a fun parallax-like fixed background effect? true/false
  text_color_light: false # Text color (true=light or false=dark).

# 看板娘配置
live2d_config:
  enable: true
  position: left
  unable_type:
    - page
