version: "3.8"

networks:
    net1:
        name: my_net #会自动创建网桥
        driver: bridge #指定网络模式
        ipam:
            driver: default
            config:
                - subnet: 172.1.1.0/24 #指定ip段

volumes:
    my_volume: #创建一个卷
        name: my_volume_name #在宿主机的目录名

# 定义一个日志模板
x-logging: &default-logging
    driver: json-file
    options:
        max-size: "200k"
        max-file: "10"

services:
    blog:
        build:
            context: ${PWD}
            dockerfile: dockerfile_hugo #指定dockerfile文件
        image: twbworld/hugo-git:latest
        container_name: blog_container_name
        hostname: blog_hostname
        working_dir: /src
        command: server
        ports:
            - 1313:1313 #如果宿主机端口不是1313,会出现调试模式失效的问题,不能自动刷新
        volumes:
            - ${PWD}/../:/src:rw #hugo项目的根目录
        environment:
            - TZ=Asia/Shanghai
            - HUGO_BIND=0.0.0.0
            - HUGO_ENV=DEV #DEV  || production
        restart: always
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.2
