#klakegg/hugo这个镜像没有git,导致hugo配置中的enableGitInfo发生报错
FROM klakegg/hugo:ubuntu

LABEL maintainer="twb<1174865138@qq.com><github.com/twbworld>"
LABEL description="构建hugo-git镜像"

RUN set -xe \
        && apt-get update \
        && apt-get install -y --no-install-recommends git
